name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'

      - name: Build with Go
        env:
          CGO_ENABLED: 0
        run: |
          GOARCH=amd64 go build -o tunmanager_linux_amd64 -ldflags="-w -s" -trimpath -v
          GOARCH=arm64 go build -o tunmanager_linux_arm64 -ldflags="-w -s" -trimpath -v

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: tunmanager_linux_*
          compression-level: 0